DROP TABLE StackoverflowPosting;
DROP TABLE Posting;
DROP TABLE Book;
DROP TABLE AuthorPublicationMapping;
DROP TABLE Publication;
DROP TABLE Author;


CREATE TABLE Author (
 id INTEGER NOT NULL,
 name VARCHAR(255),
 PRIMARY KEY (
 id
 )
);
CREATE TABLE Publication (
 id INTEGER NOT NULL,
 date TIMESTAMP,
 name VARCHAR(255),
 PRIMARY KEY (
 id
 )
);
CREATE TABLE AuthorPublicationMapping (
 id SERIAL,
 AuthorId INTEGER,
 PublicationId INTEGER,
 PRIMARY KEY (
 id
 ),
 FOREIGN KEY (AuthorId) REFERENCES AUTHOR (ID) ,
 FOREIGN KEY (PublicationId) REFERENCES PUBLICATION (ID) 
);
CREATE TABLE Book (
 ID INTEGER NOT NULL,
 ISBN VARCHAR(255),
 PRIMARY KEY (
 ID
 ),
 FOREIGN KEY (ID) REFERENCES PUBLICATION (ID) 
);
CREATE TABLE Posting (
 ID INTEGER NOT NULL,
 URL VARCHAR(255),
 PRIMARY KEY (
 ID
 ),
 FOREIGN KEY (ID) REFERENCES PUBLICATION (ID) 
);
CREATE TABLE StackoverflowPosting (
 ID INTEGER NOT NULL,
 PERMALINK VARCHAR(255),
 PRIMARY KEY (
 ID
 ),
 FOREIGN KEY (ID) REFERENCES POSTING (ID) 
);
